/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface AddBodySchema {
  a: number;
}

export interface AddQuerySchema {
  userId: string;
}

export interface ComplexBodySchema {
  a?: number;
  b: number;
  x: boolean;
}

export interface PropertiesSchemaV2 {
  dateField?: string;
  distance?: {
    fromLatitude: number;
    fromLongitude: number;
    include: boolean;
  };
  page: number;
  propertyStatus?: string;
  size: number;
  sortBy?: string;
  sortOrder?: string;
  startDate?: Date;
  territory?: string;
}
