/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface ComplexBodySchema {
  a?: number;
  b: number;
  x: boolean;
}

export interface SetMileageRequestBody {
  mileage: number;
}

export interface SetMileageRequestQueryParams {
  userId: string;
}
